name: hexlet-check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
                               
      - name: run linter check
        run: npx eslint .

