name: hexlet-check

on:
  push:
    branches:
      - origin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hexlet project check
        uses: hexlet/project-action@release
        
      - name: run linter check
        run: make lint
        
